image: sbtscala/scala-sbt:amazoncorretto-al2023-17.0.13_1.10.7_3.6.2
stages:
  - compile
  - test
  - package

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .ivy2/cache/
    - .sbt/
    - target/

before_script:
  - mkdir -p ~/.sbt ~/.ivy2
  - find ~/.ivy2/cache -name "ivydata-*.properties" -delete || true
  - find ~/.sbt -name "*.lock" -delete || true

compile:
  stage: compile
  script:
    - sbt compile
  artifacts:
    paths:
      - target

test:
  stage: test
  dependencies:
    - compile
  before_script:
    - apt-get update && apt-get install -y xvfb
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - export DISPLAY=:99
  script:
    - sbt test
  artifacts:
    reports:
      junit: target/test-reports/*.xml
    when: always

package:
  stage: package
  dependencies:
    - test
  script:
    - sbt assembly
  artifacts:
    paths:
      - target/scala-*/scala-port-forward-*.jar
  only:
    - main
    - version-1.0