port-forward {
  local-host = "127.0.0.1"
  local-port = 8090
  remote-host = "example.com"
  remote-port = 80
}

akka {
  loglevel = "INFO"
  stdout-loglevel = "INFO"
}

akka.loggers = ["akka.event.slf4j.Slf4jLogger"]
akka.logging-filter = "akka.event.slf4j.Slf4jLoggingFilter"
